# Generated by Django 3.1.7 on 2021-07-21 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('recipient', models.CharField(max_length=64)),
                ('inflow', models.DecimalField(decimal_places=2, max_digits=8)),
                ('outflow', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=datetime.date.today)),
                ('allocated', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disbursed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.category')),
            ],
            options={
                'get_latest_by': 'month',
            },
        ),
    ]
