# Generated by Django 3.1.7 on 2021-07-18 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'get_latest_by': 'month'},
        ),
    ]
