# Generated by Django 3.1.7 on 2021-08-13 01:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('name', models.CharField(max_length=64)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Brokerage Account'), (2, 'Traditional IRA'), (3, 'Roth IRA'), (4, 'Health Savings Account'), (5, 'Traditional 401k'), (6, 'Roth 401k'), (7, '529 College Savings Account')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ticker', models.CharField(max_length=5)),
                ('shares', models.DecimalField(decimal_places=3, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_app.assetaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_app.assetaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
