# Generated by Django 3.1.7 on 2021-07-19 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
